### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by blitzwilli** [pooliestudios/linkmotor#7]
hallo 

bekomme nach der Installation HTTP ERROR 500 
und der Error Log: 
[Mon Sep 05 16:01:08.695655 2016] [:error] [pid 7112] [client 172.16.36.1:54883] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to write cache file "/var/www/lphr.de/htdocs/linkmotor/app/cache/prod/classes.php".' in /var/www/lphr.de/htdocs/linkmotor/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:239\nStack trace:\n#0 /var/www/lphr.de/htdocs/linkmotor/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(122): Symfony\\Component\\ClassLoader\\ClassCollectionLoader::writeCacheFile('/var/www/lphr.d...', '<?php \\nnamespac...')\n#1 /var/www/lphr.de/htdocs/linkmotor/app/bootstrap.php.cache(2434): Symfony\\Component\\ClassLoader\\ClassCollectionLoader::load(Array, '/var/www/lphr.d...', 'classes', false, false, '.php')\n#2 /var/www/lphr.de/htdocs/linkmotor/app/bootstrap.php.cache(2270): Symfony\\Component\\HttpKernel\\Kernel->doLoadClassCache('classes', '.php')\n#3 /var/www/lphr.de/htdocs/linkmotor/app/bootstrap.php.cache(2304): Symfony\\Component\\HttpKernel\\Kernel->boot()\n#4 /var/www/lphr.de/htdocs/linkmotor/web/app.php(12): Symfony\\C in /var/www/lphr.de/htdocs/linkmotor/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php on line 239

kannst du mir da vielleicht weiterhelfen ?
Danke.

Schmidt

**Comment by b3nelof0n** [comment]
Hast du Schreibrechte in /var/www/lphr.de/htdocs/linkmotor/app/cache/ ?

**Comment by dolbertz** [comment]
Ja, das ist das Problem: "**Failed to write cache file "/var/www/lphr.de/htdocs/linkmotor/app/cache/prod/classes.php**"

Der Webserver muss alles unterhal von app/cache und app/logs beschreiben können. Siehe auch den Punkt 5 der Installationsanleitung.

**Comment by blitzwilli** [comment]
habe jetzt mit chmod -R 777 alle Ordner die rechte gegeben 
aber jetzt kommt die Meldung

Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by dolbertz** [comment]
Was sagt denn das app/log/prod.log?

**Comment by blitzwilli** [comment]
[2016-09-05 16:25:05] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2016-09-05 16:25:05] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Intl\Exception\MethodNotImplementedException: "The Symfony\Component\Intl\Locale\Locale::getPrimaryLanguage() is not implemented. Please install the "intl" extension for full localization capabilities." at /var/www/lphr.de/htdocs/linkmotor/vendor/symfony/symfony/src/Symfony/Component/Intl/Locale/Locale.php line 234 {"exception":"[object] (Symfony\\Component\\Intl\\Exception\\MethodNotImplementedException(code: 0): The Symfony\\Component\\Intl\\Locale\\Locale::getPrimaryLanguage() is not implemented. Please install the \"intl\" extension for full localization capabilities. at /var/www/lphr.de/htdocs/linkmotor/vendor/symfony/symfony/src/Symfony/Component/Intl/Locale/Locale.php:234)"} []
[2016-09-05 16:25:05] security.DEBUG: Write SecurityContext in the session [] []

**Comment by dolbertz** [comment]
**Please install the "intl" extension for full localization capabilities.**
